# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vtpl_api
from vtpl_api.models.object_indirect_properties import ObjectIndirectProperties  # noqa: E501
from vtpl_api.rest import ApiException


class TestObjectIndirectProperties(unittest.TestCase):
    """ObjectIndirectProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectIndirectProperties(self):
        """Test ObjectIndirectProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vtpl_api.models.object_indirect_properties.ObjectIndirectProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
