# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.destination_end_point import DestinationEndPoint  # noqa: E501
from swagger_client.rest import ApiException


class TestDestinationEndPoint(unittest.TestCase):
    """DestinationEndPoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinationEndPoint(self):
        """Test DestinationEndPoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.destination_end_point.DestinationEndPoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
