# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vtpl_api
from vtpl_api.models.engine_task_status_response import EngineTaskStatusResponse  # noqa: E501
from vtpl_api.rest import ApiException


class TestEngineTaskStatusResponse(unittest.TestCase):
    """EngineTaskStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEngineTaskStatusResponse(self):
        """Test EngineTaskStatusResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vtpl_api.models.engine_task_status_response.EngineTaskStatusResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
