# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.engine import Engine  # noqa: E501
from swagger_client.rest import ApiException


class TestEngine(unittest.TestCase):
    """Engine unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEngine(self):
        """Test Engine"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.engine.Engine()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
