# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.object_direct_properties import ObjectDirectProperties  # noqa: E501
from swagger_client.rest import ApiException


class TestObjectDirectProperties(unittest.TestCase):
    """ObjectDirectProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectDirectProperties(self):
        """Test ObjectDirectProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.object_direct_properties.ObjectDirectProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
