# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pre_processes_response import PreProcessesResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestPreProcessesResponse(unittest.TestCase):
    """PreProcessesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreProcessesResponse(self):
        """Test PreProcessesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pre_processes_response.PreProcessesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
