# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inferencer import Inferencer  # noqa: E501
from swagger_client.rest import ApiException


class TestInferencer(unittest.TestCase):
    """Inferencer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInferencer(self):
        """Test Inferencer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inferencer.Inferencer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
