# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vtpl_api
from vtpl_api.models.href import Href  # noqa: E501
from vtpl_api.rest import ApiException


class TestHref(unittest.TestCase):
    """Href unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHref(self):
        """Test Href"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vtpl_api.models.href.Href()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
