# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import vtpl_api
from vtpl_api.models.precis_engine_task import PrecisEngineTask  # noqa: E501
from vtpl_api.rest import ApiException


class TestPrecisEngineTask(unittest.TestCase):
    """PrecisEngineTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrecisEngineTask(self):
        """Test PrecisEngineTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vtpl_api.models.precis_engine_task.PrecisEngineTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
