# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.evidence_config import EvidenceConfig  # noqa: E501
from swagger_client.rest import ApiException


class TestEvidenceConfig(unittest.TestCase):
    """EvidenceConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEvidenceConfig(self):
        """Test EvidenceConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.evidence_config.EvidenceConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
