# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.engine_task_status import EngineTaskStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestEngineTaskStatus(unittest.TestCase):
    """EngineTaskStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEngineTaskStatus(self):
        """Test EngineTaskStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.engine_task_status.EngineTaskStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
