# coding: utf-8

# flake8: noqa

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.engines_api import EnginesApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.animal_properties import AnimalProperties
from swagger_client.models.anpr_event import AnprEvent
from swagger_client.models.anpr_events_response import AnprEventsResponse
from swagger_client.models.attribute_event import AttributeEvent
from swagger_client.models.attribute_events_response import AttributeEventsResponse
from swagger_client.models.capability import Capability
from swagger_client.models.clip import Clip
from swagger_client.models.clips_response import ClipsResponse
from swagger_client.models.color import Color
from swagger_client.models.config import Config
from swagger_client.models.default_response import DefaultResponse
from swagger_client.models.destination_end_point import DestinationEndPoint
from swagger_client.models.destination_end_point_destination_list import DestinationEndPointDestinationList
from swagger_client.models.destination_type import DestinationType
from swagger_client.models.engine import Engine
from swagger_client.models.engine_task import EngineTask
from swagger_client.models.engine_task_line_setting import EngineTaskLineSetting
from swagger_client.models.engine_task_status import EngineTaskStatus
from swagger_client.models.engine_task_status_cumulative import EngineTaskStatusCumulative
from swagger_client.models.engine_task_status_failure import EngineTaskStatusFailure
from swagger_client.models.engine_task_status_progress import EngineTaskStatusProgress
from swagger_client.models.engine_task_status_response import EngineTaskStatusResponse
from swagger_client.models.engine_task_zone_setting import EngineTaskZoneSetting
from swagger_client.models.engine_tasks_response import EngineTasksResponse
from swagger_client.models.engines_response import EnginesResponse
from swagger_client.models.event import Event
from swagger_client.models.event_details import EventDetails
from swagger_client.models.event_snaps_response import EventSnapsResponse
from swagger_client.models.event_type import EventType
from swagger_client.models.evidence_config import EvidenceConfig
from swagger_client.models.extra import Extra
from swagger_client.models.href import Href
from swagger_client.models.human_properties import HumanProperties
from swagger_client.models.inferencer import Inferencer
from swagger_client.models.inferencers_response import InferencersResponse
from swagger_client.models.license_plate_details import LicensePlateDetails
from swagger_client.models.line import Line
from swagger_client.models.line_type import LineType
from swagger_client.models.links import Links
from swagger_client.models.links_self import LinksSelf
from swagger_client.models.links_self_self import LinksSelfSelf
from swagger_client.models.media_source_response import MediaSourceResponse
from swagger_client.models.meta import Meta
from swagger_client.models.meta_anpr_event import MetaAnprEvent
from swagger_client.models.meta_attribute_event import MetaAttributeEvent
from swagger_client.models.meta_va_event import MetaVaEvent
from swagger_client.models.motion_detector import MotionDetector
from swagger_client.models.motion_detectors_response import MotionDetectorsResponse
from swagger_client.models.object_dimension import ObjectDimension
from swagger_client.models.object_direct_properties import ObjectDirectProperties
from swagger_client.models.object_indirect_properties import ObjectIndirectProperties
from swagger_client.models.object_info import ObjectInfo
from swagger_client.models.object_rect import ObjectRect
from swagger_client.models.object_rect_with_time_stamp_and_event_snap_reference import ObjectRectWithTimeStampAndEventSnapReference
from swagger_client.models.pipeline import Pipeline
from swagger_client.models.pipelines_response import PipelinesResponse
from swagger_client.models.pre_process import PreProcess
from swagger_client.models.pre_processes_response import PreProcessesResponse
from swagger_client.models.precis_engine_task import PrecisEngineTask
from swagger_client.models.precis_engine_task_status import PrecisEngineTaskStatus
from swagger_client.models.precis_engine_task_status_progress import PrecisEngineTaskStatusProgress
from swagger_client.models.precis_engine_task_status_response import PrecisEngineTaskStatusResponse
from swagger_client.models.precis_engine_tasks_response import PrecisEngineTasksResponse
from swagger_client.models.schedule_source import ScheduleSource
from swagger_client.models.snap import Snap
from swagger_client.models.snaps_response import SnapsResponse
from swagger_client.models.source_end_point import SourceEndPoint
from swagger_client.models.source_end_point_source_list import SourceEndPointSourceList
from swagger_client.models.source_type import SourceType
from swagger_client.models.title import Title
from swagger_client.models.track_properties import TrackProperties
from swagger_client.models.va_event import VaEvent
from swagger_client.models.va_events_response import VaEventsResponse
from swagger_client.models.vehicle_properties import VehicleProperties
from swagger_client.models.vehicle_type import VehicleType
from swagger_client.models.vertex import Vertex
from swagger_client.models.vtpl_video_frame import VtplVideoFrame
from swagger_client.models.zone import Zone
from swagger_client.models.zone_type import ZoneType
