# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PrecisEngineTask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'user_id': 'str',
        'capbilities_type': 'Capability',
        'event_type': 'EventType',
        'engine_machine_id': 'str',
        'is_expired': 'bool',
        'result_url': 'str',
        'children': 'list[Capability]',
        'start_time_stamp': 'int',
        'end_time_stamp': 'int',
        'time_to_live': 'int',
        'source_end_point_id': 'str',
        'destination': 'DestinationEndPoint',
        'extras': 'list[Extra]',
        'zone_setting': 'EngineTaskZoneSetting',
        'line_setting': 'EngineTaskLineSetting',
        'config': 'list[Config]',
        'meta_attribute_event': 'MetaAttributeEvent',
        'updated': 'datetime',
        'created': 'datetime',
        'etag': 'str',
        'links': 'Links'
    }

    attribute_map = {
        'id': '_id',
        'user_id': 'userId',
        'capbilities_type': 'capbilitiesType',
        'event_type': 'eventType',
        'engine_machine_id': 'engineMachineId',
        'is_expired': 'isExpired',
        'result_url': 'resultUrl',
        'children': 'children',
        'start_time_stamp': 'startTimeStamp',
        'end_time_stamp': 'endTimeStamp',
        'time_to_live': 'timeToLive',
        'source_end_point_id': 'sourceEndPointId',
        'destination': 'destination',
        'extras': 'extras',
        'zone_setting': 'zoneSetting',
        'line_setting': 'lineSetting',
        'config': 'config',
        'meta_attribute_event': 'metaAttributeEvent',
        'updated': 'updated',
        'created': 'created',
        'etag': 'etag',
        'links': 'links'
    }

    def __init__(self, id=None, user_id=None, capbilities_type=None, event_type=None, engine_machine_id=None, is_expired=False, result_url=None, children=None, start_time_stamp=None, end_time_stamp=None, time_to_live=-1, source_end_point_id=None, destination=None, extras=None, zone_setting=None, line_setting=None, config=None, meta_attribute_event=None, updated=None, created=None, etag=None, links=None):  # noqa: E501
        """PrecisEngineTask - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._user_id = None
        self._capbilities_type = None
        self._event_type = None
        self._engine_machine_id = None
        self._is_expired = None
        self._result_url = None
        self._children = None
        self._start_time_stamp = None
        self._end_time_stamp = None
        self._time_to_live = None
        self._source_end_point_id = None
        self._destination = None
        self._extras = None
        self._zone_setting = None
        self._line_setting = None
        self._config = None
        self._meta_attribute_event = None
        self._updated = None
        self._created = None
        self._etag = None
        self._links = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if user_id is not None:
            self.user_id = user_id
        if capbilities_type is not None:
            self.capbilities_type = capbilities_type
        if event_type is not None:
            self.event_type = event_type
        if engine_machine_id is not None:
            self.engine_machine_id = engine_machine_id
        if is_expired is not None:
            self.is_expired = is_expired
        if result_url is not None:
            self.result_url = result_url
        if children is not None:
            self.children = children
        if start_time_stamp is not None:
            self.start_time_stamp = start_time_stamp
        if end_time_stamp is not None:
            self.end_time_stamp = end_time_stamp
        if time_to_live is not None:
            self.time_to_live = time_to_live
        if source_end_point_id is not None:
            self.source_end_point_id = source_end_point_id
        if destination is not None:
            self.destination = destination
        if extras is not None:
            self.extras = extras
        if zone_setting is not None:
            self.zone_setting = zone_setting
        if line_setting is not None:
            self.line_setting = line_setting
        if config is not None:
            self.config = config
        if meta_attribute_event is not None:
            self.meta_attribute_event = meta_attribute_event
        if updated is not None:
            self.updated = updated
        if created is not None:
            self.created = created
        if etag is not None:
            self.etag = etag
        if links is not None:
            self.links = links

    @property
    def id(self):
        """Gets the id of this PrecisEngineTask.  # noqa: E501


        :return: The id of this PrecisEngineTask.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PrecisEngineTask.


        :param id: The id of this PrecisEngineTask.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def user_id(self):
        """Gets the user_id of this PrecisEngineTask.  # noqa: E501


        :return: The user_id of this PrecisEngineTask.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this PrecisEngineTask.


        :param user_id: The user_id of this PrecisEngineTask.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def capbilities_type(self):
        """Gets the capbilities_type of this PrecisEngineTask.  # noqa: E501


        :return: The capbilities_type of this PrecisEngineTask.  # noqa: E501
        :rtype: Capability
        """
        return self._capbilities_type

    @capbilities_type.setter
    def capbilities_type(self, capbilities_type):
        """Sets the capbilities_type of this PrecisEngineTask.


        :param capbilities_type: The capbilities_type of this PrecisEngineTask.  # noqa: E501
        :type: Capability
        """

        self._capbilities_type = capbilities_type

    @property
    def event_type(self):
        """Gets the event_type of this PrecisEngineTask.  # noqa: E501


        :return: The event_type of this PrecisEngineTask.  # noqa: E501
        :rtype: EventType
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type):
        """Sets the event_type of this PrecisEngineTask.


        :param event_type: The event_type of this PrecisEngineTask.  # noqa: E501
        :type: EventType
        """

        self._event_type = event_type

    @property
    def engine_machine_id(self):
        """Gets the engine_machine_id of this PrecisEngineTask.  # noqa: E501


        :return: The engine_machine_id of this PrecisEngineTask.  # noqa: E501
        :rtype: str
        """
        return self._engine_machine_id

    @engine_machine_id.setter
    def engine_machine_id(self, engine_machine_id):
        """Sets the engine_machine_id of this PrecisEngineTask.


        :param engine_machine_id: The engine_machine_id of this PrecisEngineTask.  # noqa: E501
        :type: str
        """

        self._engine_machine_id = engine_machine_id

    @property
    def is_expired(self):
        """Gets the is_expired of this PrecisEngineTask.  # noqa: E501

        Explanations: * true = Engines will NEVER execute this task * false = Engines will execute this task * Engine must patch this flag to true when completes processing or have found \"timeToLive\" has passed task creation time  # noqa: E501

        :return: The is_expired of this PrecisEngineTask.  # noqa: E501
        :rtype: bool
        """
        return self._is_expired

    @is_expired.setter
    def is_expired(self, is_expired):
        """Sets the is_expired of this PrecisEngineTask.

        Explanations: * true = Engines will NEVER execute this task * false = Engines will execute this task * Engine must patch this flag to true when completes processing or have found \"timeToLive\" has passed task creation time  # noqa: E501

        :param is_expired: The is_expired of this PrecisEngineTask.  # noqa: E501
        :type: bool
        """

        self._is_expired = is_expired

    @property
    def result_url(self):
        """Gets the result_url of this PrecisEngineTask.  # noqa: E501


        :return: The result_url of this PrecisEngineTask.  # noqa: E501
        :rtype: str
        """
        return self._result_url

    @result_url.setter
    def result_url(self, result_url):
        """Sets the result_url of this PrecisEngineTask.


        :param result_url: The result_url of this PrecisEngineTask.  # noqa: E501
        :type: str
        """

        self._result_url = result_url

    @property
    def children(self):
        """Gets the children of this PrecisEngineTask.  # noqa: E501


        :return: The children of this PrecisEngineTask.  # noqa: E501
        :rtype: list[Capability]
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this PrecisEngineTask.


        :param children: The children of this PrecisEngineTask.  # noqa: E501
        :type: list[Capability]
        """

        self._children = children

    @property
    def start_time_stamp(self):
        """Gets the start_time_stamp of this PrecisEngineTask.  # noqa: E501

        EngineTask processing start time  # noqa: E501

        :return: The start_time_stamp of this PrecisEngineTask.  # noqa: E501
        :rtype: int
        """
        return self._start_time_stamp

    @start_time_stamp.setter
    def start_time_stamp(self, start_time_stamp):
        """Sets the start_time_stamp of this PrecisEngineTask.

        EngineTask processing start time  # noqa: E501

        :param start_time_stamp: The start_time_stamp of this PrecisEngineTask.  # noqa: E501
        :type: int
        """

        self._start_time_stamp = start_time_stamp

    @property
    def end_time_stamp(self):
        """Gets the end_time_stamp of this PrecisEngineTask.  # noqa: E501

        EngineTask processing end time  # noqa: E501

        :return: The end_time_stamp of this PrecisEngineTask.  # noqa: E501
        :rtype: int
        """
        return self._end_time_stamp

    @end_time_stamp.setter
    def end_time_stamp(self, end_time_stamp):
        """Sets the end_time_stamp of this PrecisEngineTask.

        EngineTask processing end time  # noqa: E501

        :param end_time_stamp: The end_time_stamp of this PrecisEngineTask.  # noqa: E501
        :type: int
        """

        self._end_time_stamp = end_time_stamp

    @property
    def time_to_live(self):
        """Gets the time_to_live of this PrecisEngineTask.  # noqa: E501

        Time in milliseconds of expiry or the task. Engines will not execute an expired task. Explanations: * -1 = Never expires * -2 = Expired *  0 = Will expire in 0 milliseconds * >0 = This task is invalid and must not be executed after >0 milliseconds from task creation time  # noqa: E501

        :return: The time_to_live of this PrecisEngineTask.  # noqa: E501
        :rtype: int
        """
        return self._time_to_live

    @time_to_live.setter
    def time_to_live(self, time_to_live):
        """Sets the time_to_live of this PrecisEngineTask.

        Time in milliseconds of expiry or the task. Engines will not execute an expired task. Explanations: * -1 = Never expires * -2 = Expired *  0 = Will expire in 0 milliseconds * >0 = This task is invalid and must not be executed after >0 milliseconds from task creation time  # noqa: E501

        :param time_to_live: The time_to_live of this PrecisEngineTask.  # noqa: E501
        :type: int
        """

        self._time_to_live = time_to_live

    @property
    def source_end_point_id(self):
        """Gets the source_end_point_id of this PrecisEngineTask.  # noqa: E501

        _id of snap from #$ref: '#/components/schemas/sourceEndPoint'  # noqa: E501

        :return: The source_end_point_id of this PrecisEngineTask.  # noqa: E501
        :rtype: str
        """
        return self._source_end_point_id

    @source_end_point_id.setter
    def source_end_point_id(self, source_end_point_id):
        """Sets the source_end_point_id of this PrecisEngineTask.

        _id of snap from #$ref: '#/components/schemas/sourceEndPoint'  # noqa: E501

        :param source_end_point_id: The source_end_point_id of this PrecisEngineTask.  # noqa: E501
        :type: str
        """

        self._source_end_point_id = source_end_point_id

    @property
    def destination(self):
        """Gets the destination of this PrecisEngineTask.  # noqa: E501


        :return: The destination of this PrecisEngineTask.  # noqa: E501
        :rtype: DestinationEndPoint
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this PrecisEngineTask.


        :param destination: The destination of this PrecisEngineTask.  # noqa: E501
        :type: DestinationEndPoint
        """

        self._destination = destination

    @property
    def extras(self):
        """Gets the extras of this PrecisEngineTask.  # noqa: E501


        :return: The extras of this PrecisEngineTask.  # noqa: E501
        :rtype: list[Extra]
        """
        return self._extras

    @extras.setter
    def extras(self, extras):
        """Sets the extras of this PrecisEngineTask.


        :param extras: The extras of this PrecisEngineTask.  # noqa: E501
        :type: list[Extra]
        """

        self._extras = extras

    @property
    def zone_setting(self):
        """Gets the zone_setting of this PrecisEngineTask.  # noqa: E501


        :return: The zone_setting of this PrecisEngineTask.  # noqa: E501
        :rtype: EngineTaskZoneSetting
        """
        return self._zone_setting

    @zone_setting.setter
    def zone_setting(self, zone_setting):
        """Sets the zone_setting of this PrecisEngineTask.


        :param zone_setting: The zone_setting of this PrecisEngineTask.  # noqa: E501
        :type: EngineTaskZoneSetting
        """

        self._zone_setting = zone_setting

    @property
    def line_setting(self):
        """Gets the line_setting of this PrecisEngineTask.  # noqa: E501


        :return: The line_setting of this PrecisEngineTask.  # noqa: E501
        :rtype: EngineTaskLineSetting
        """
        return self._line_setting

    @line_setting.setter
    def line_setting(self, line_setting):
        """Sets the line_setting of this PrecisEngineTask.


        :param line_setting: The line_setting of this PrecisEngineTask.  # noqa: E501
        :type: EngineTaskLineSetting
        """

        self._line_setting = line_setting

    @property
    def config(self):
        """Gets the config of this PrecisEngineTask.  # noqa: E501


        :return: The config of this PrecisEngineTask.  # noqa: E501
        :rtype: list[Config]
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this PrecisEngineTask.


        :param config: The config of this PrecisEngineTask.  # noqa: E501
        :type: list[Config]
        """

        self._config = config

    @property
    def meta_attribute_event(self):
        """Gets the meta_attribute_event of this PrecisEngineTask.  # noqa: E501


        :return: The meta_attribute_event of this PrecisEngineTask.  # noqa: E501
        :rtype: MetaAttributeEvent
        """
        return self._meta_attribute_event

    @meta_attribute_event.setter
    def meta_attribute_event(self, meta_attribute_event):
        """Sets the meta_attribute_event of this PrecisEngineTask.


        :param meta_attribute_event: The meta_attribute_event of this PrecisEngineTask.  # noqa: E501
        :type: MetaAttributeEvent
        """

        self._meta_attribute_event = meta_attribute_event

    @property
    def updated(self):
        """Gets the updated of this PrecisEngineTask.  # noqa: E501


        :return: The updated of this PrecisEngineTask.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this PrecisEngineTask.


        :param updated: The updated of this PrecisEngineTask.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def created(self):
        """Gets the created of this PrecisEngineTask.  # noqa: E501


        :return: The created of this PrecisEngineTask.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this PrecisEngineTask.


        :param created: The created of this PrecisEngineTask.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def etag(self):
        """Gets the etag of this PrecisEngineTask.  # noqa: E501


        :return: The etag of this PrecisEngineTask.  # noqa: E501
        :rtype: str
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this PrecisEngineTask.


        :param etag: The etag of this PrecisEngineTask.  # noqa: E501
        :type: str
        """

        self._etag = etag

    @property
    def links(self):
        """Gets the links of this PrecisEngineTask.  # noqa: E501


        :return: The links of this PrecisEngineTask.  # noqa: E501
        :rtype: Links
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PrecisEngineTask.


        :param links: The links of this PrecisEngineTask.  # noqa: E501
        :type: Links
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PrecisEngineTask, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrecisEngineTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
