# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TrackProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'track_id': 'int',
        'track_length': 'int'
    }

    attribute_map = {
        'track_id': 'trackId',
        'track_length': 'trackLength'
    }

    def __init__(self, track_id=-1, track_length=-1):  # noqa: E501
        """TrackProperties - a model defined in Swagger"""  # noqa: E501
        self._track_id = None
        self._track_length = None
        self.discriminator = None
        if track_id is not None:
            self.track_id = track_id
        if track_length is not None:
            self.track_length = track_length

    @property
    def track_id(self):
        """Gets the track_id of this TrackProperties.  # noqa: E501


        :return: The track_id of this TrackProperties.  # noqa: E501
        :rtype: int
        """
        return self._track_id

    @track_id.setter
    def track_id(self, track_id):
        """Sets the track_id of this TrackProperties.


        :param track_id: The track_id of this TrackProperties.  # noqa: E501
        :type: int
        """

        self._track_id = track_id

    @property
    def track_length(self):
        """Gets the track_length of this TrackProperties.  # noqa: E501


        :return: The track_length of this TrackProperties.  # noqa: E501
        :rtype: int
        """
        return self._track_length

    @track_length.setter
    def track_length(self, track_length):
        """Sets the track_length of this TrackProperties.


        :param track_length: The track_length of this TrackProperties.  # noqa: E501
        :type: int
        """

        self._track_length = track_length

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackProperties, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackProperties):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
