/*
 * Videonetics Visual Computing Platform
 * API to access the Videonetics Visual Computing Platform for analytics events
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Event;
import io.swagger.client.model.Events;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EventsApi
 */
@Ignore
public class EventsApiTest {

    private final EventsApi api = new EventsApi();

    /**
     * Get events list
     *
     * List all the events available.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enterpriseIdEventsGetTest() throws ApiException {
        UUID enterpriseId = null;
        Events response = api.enterpriseIdEventsGet(enterpriseId);

        // TODO: test validations
    }
    /**
     * Create new event
     *
     * Create new event.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enterpriseIdEventsPostTest() throws ApiException {
        UUID enterpriseId = null;
        Event response = api.enterpriseIdEventsPost(enterpriseId);

        // TODO: test validations
    }
}
