# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MetaAttributeEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'estimated_height': 'int',
        'top_type': 'str',
        'top_color': 'str',
        'bottom_type': 'str',
        'bottom_color': 'str',
        'sex': 'str',
        'presence_of_bag': 'bool',
        'type_of_bag': 'str',
        'clothing_pattern': 'str',
        'presence_of_heade_dress': 'bool',
        'type_of_head_dress': 'str',
        'associated_object': 'str'
    }

    attribute_map = {
        'estimated_height': 'estimatedHeight',
        'top_type': 'topType',
        'top_color': 'topColor',
        'bottom_type': 'bottomType',
        'bottom_color': 'bottomColor',
        'sex': 'sex',
        'presence_of_bag': 'presenceOfBag',
        'type_of_bag': 'typeOfBag',
        'clothing_pattern': 'clothingPattern',
        'presence_of_heade_dress': 'presenceOfHeadeDress',
        'type_of_head_dress': 'typeOfHeadDress',
        'associated_object': 'associatedObject'
    }

    def __init__(self, estimated_height=0, top_type=None, top_color=None, bottom_type=None, bottom_color=None, sex=None, presence_of_bag=None, type_of_bag=None, clothing_pattern=None, presence_of_heade_dress=None, type_of_head_dress=None, associated_object=None):  # noqa: E501
        """MetaAttributeEvent - a model defined in Swagger"""  # noqa: E501
        self._estimated_height = None
        self._top_type = None
        self._top_color = None
        self._bottom_type = None
        self._bottom_color = None
        self._sex = None
        self._presence_of_bag = None
        self._type_of_bag = None
        self._clothing_pattern = None
        self._presence_of_heade_dress = None
        self._type_of_head_dress = None
        self._associated_object = None
        self.discriminator = None
        if estimated_height is not None:
            self.estimated_height = estimated_height
        if top_type is not None:
            self.top_type = top_type
        if top_color is not None:
            self.top_color = top_color
        if bottom_type is not None:
            self.bottom_type = bottom_type
        if bottom_color is not None:
            self.bottom_color = bottom_color
        if sex is not None:
            self.sex = sex
        if presence_of_bag is not None:
            self.presence_of_bag = presence_of_bag
        if type_of_bag is not None:
            self.type_of_bag = type_of_bag
        if clothing_pattern is not None:
            self.clothing_pattern = clothing_pattern
        if presence_of_heade_dress is not None:
            self.presence_of_heade_dress = presence_of_heade_dress
        if type_of_head_dress is not None:
            self.type_of_head_dress = type_of_head_dress
        if associated_object is not None:
            self.associated_object = associated_object

    @property
    def estimated_height(self):
        """Gets the estimated_height of this MetaAttributeEvent.  # noqa: E501


        :return: The estimated_height of this MetaAttributeEvent.  # noqa: E501
        :rtype: int
        """
        return self._estimated_height

    @estimated_height.setter
    def estimated_height(self, estimated_height):
        """Sets the estimated_height of this MetaAttributeEvent.


        :param estimated_height: The estimated_height of this MetaAttributeEvent.  # noqa: E501
        :type: int
        """

        self._estimated_height = estimated_height

    @property
    def top_type(self):
        """Gets the top_type of this MetaAttributeEvent.  # noqa: E501


        :return: The top_type of this MetaAttributeEvent.  # noqa: E501
        :rtype: str
        """
        return self._top_type

    @top_type.setter
    def top_type(self, top_type):
        """Sets the top_type of this MetaAttributeEvent.


        :param top_type: The top_type of this MetaAttributeEvent.  # noqa: E501
        :type: str
        """

        self._top_type = top_type

    @property
    def top_color(self):
        """Gets the top_color of this MetaAttributeEvent.  # noqa: E501


        :return: The top_color of this MetaAttributeEvent.  # noqa: E501
        :rtype: str
        """
        return self._top_color

    @top_color.setter
    def top_color(self, top_color):
        """Sets the top_color of this MetaAttributeEvent.


        :param top_color: The top_color of this MetaAttributeEvent.  # noqa: E501
        :type: str
        """

        self._top_color = top_color

    @property
    def bottom_type(self):
        """Gets the bottom_type of this MetaAttributeEvent.  # noqa: E501


        :return: The bottom_type of this MetaAttributeEvent.  # noqa: E501
        :rtype: str
        """
        return self._bottom_type

    @bottom_type.setter
    def bottom_type(self, bottom_type):
        """Sets the bottom_type of this MetaAttributeEvent.


        :param bottom_type: The bottom_type of this MetaAttributeEvent.  # noqa: E501
        :type: str
        """

        self._bottom_type = bottom_type

    @property
    def bottom_color(self):
        """Gets the bottom_color of this MetaAttributeEvent.  # noqa: E501


        :return: The bottom_color of this MetaAttributeEvent.  # noqa: E501
        :rtype: str
        """
        return self._bottom_color

    @bottom_color.setter
    def bottom_color(self, bottom_color):
        """Sets the bottom_color of this MetaAttributeEvent.


        :param bottom_color: The bottom_color of this MetaAttributeEvent.  # noqa: E501
        :type: str
        """

        self._bottom_color = bottom_color

    @property
    def sex(self):
        """Gets the sex of this MetaAttributeEvent.  # noqa: E501


        :return: The sex of this MetaAttributeEvent.  # noqa: E501
        :rtype: str
        """
        return self._sex

    @sex.setter
    def sex(self, sex):
        """Sets the sex of this MetaAttributeEvent.


        :param sex: The sex of this MetaAttributeEvent.  # noqa: E501
        :type: str
        """

        self._sex = sex

    @property
    def presence_of_bag(self):
        """Gets the presence_of_bag of this MetaAttributeEvent.  # noqa: E501


        :return: The presence_of_bag of this MetaAttributeEvent.  # noqa: E501
        :rtype: bool
        """
        return self._presence_of_bag

    @presence_of_bag.setter
    def presence_of_bag(self, presence_of_bag):
        """Sets the presence_of_bag of this MetaAttributeEvent.


        :param presence_of_bag: The presence_of_bag of this MetaAttributeEvent.  # noqa: E501
        :type: bool
        """

        self._presence_of_bag = presence_of_bag

    @property
    def type_of_bag(self):
        """Gets the type_of_bag of this MetaAttributeEvent.  # noqa: E501


        :return: The type_of_bag of this MetaAttributeEvent.  # noqa: E501
        :rtype: str
        """
        return self._type_of_bag

    @type_of_bag.setter
    def type_of_bag(self, type_of_bag):
        """Sets the type_of_bag of this MetaAttributeEvent.


        :param type_of_bag: The type_of_bag of this MetaAttributeEvent.  # noqa: E501
        :type: str
        """

        self._type_of_bag = type_of_bag

    @property
    def clothing_pattern(self):
        """Gets the clothing_pattern of this MetaAttributeEvent.  # noqa: E501


        :return: The clothing_pattern of this MetaAttributeEvent.  # noqa: E501
        :rtype: str
        """
        return self._clothing_pattern

    @clothing_pattern.setter
    def clothing_pattern(self, clothing_pattern):
        """Sets the clothing_pattern of this MetaAttributeEvent.


        :param clothing_pattern: The clothing_pattern of this MetaAttributeEvent.  # noqa: E501
        :type: str
        """

        self._clothing_pattern = clothing_pattern

    @property
    def presence_of_heade_dress(self):
        """Gets the presence_of_heade_dress of this MetaAttributeEvent.  # noqa: E501


        :return: The presence_of_heade_dress of this MetaAttributeEvent.  # noqa: E501
        :rtype: bool
        """
        return self._presence_of_heade_dress

    @presence_of_heade_dress.setter
    def presence_of_heade_dress(self, presence_of_heade_dress):
        """Sets the presence_of_heade_dress of this MetaAttributeEvent.


        :param presence_of_heade_dress: The presence_of_heade_dress of this MetaAttributeEvent.  # noqa: E501
        :type: bool
        """

        self._presence_of_heade_dress = presence_of_heade_dress

    @property
    def type_of_head_dress(self):
        """Gets the type_of_head_dress of this MetaAttributeEvent.  # noqa: E501


        :return: The type_of_head_dress of this MetaAttributeEvent.  # noqa: E501
        :rtype: str
        """
        return self._type_of_head_dress

    @type_of_head_dress.setter
    def type_of_head_dress(self, type_of_head_dress):
        """Sets the type_of_head_dress of this MetaAttributeEvent.


        :param type_of_head_dress: The type_of_head_dress of this MetaAttributeEvent.  # noqa: E501
        :type: str
        """

        self._type_of_head_dress = type_of_head_dress

    @property
    def associated_object(self):
        """Gets the associated_object of this MetaAttributeEvent.  # noqa: E501


        :return: The associated_object of this MetaAttributeEvent.  # noqa: E501
        :rtype: str
        """
        return self._associated_object

    @associated_object.setter
    def associated_object(self, associated_object):
        """Sets the associated_object of this MetaAttributeEvent.


        :param associated_object: The associated_object of this MetaAttributeEvent.  # noqa: E501
        :type: str
        """

        self._associated_object = associated_object

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MetaAttributeEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetaAttributeEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
