/*
 * Videonetics Visual Computing Platform
 * API to access the Videonetics Visual Computing Platform for analytics events
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.LinksSelf;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * DefaultResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-09T12:31:58.860Z[GMT]")
public class DefaultResponse {
  @SerializedName("_id")
  private String _id = null;

  @SerializedName("updated")
  private OffsetDateTime updated = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("etag")
  private String etag = null;

  @SerializedName("links")
  private LinksSelf links = null;

  @SerializedName("status")
  private String status = null;

   /**
   * Get _id
   * @return _id
  **/
  @Schema(example = "5c1956e925b6b30001103eb6", description = "")
  public String getId() {
    return _id;
  }

   /**
   * Get updated
   * @return updated
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdated() {
    return updated;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(description = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public DefaultResponse etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * Get etag
   * @return etag
  **/
  @Schema(example = "f7d6f2133d892ca3be7ee54d77c14bb15f75f72e", description = "")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }

  public DefaultResponse links(LinksSelf links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @Schema(description = "")
  public LinksSelf getLinks() {
    return links;
  }

  public void setLinks(LinksSelf links) {
    this.links = links;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(example = "OK", description = "")
  public String getStatus() {
    return status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DefaultResponse defaultResponse = (DefaultResponse) o;
    return Objects.equals(this._id, defaultResponse._id) &&
        Objects.equals(this.updated, defaultResponse.updated) &&
        Objects.equals(this.created, defaultResponse.created) &&
        Objects.equals(this.etag, defaultResponse.etag) &&
        Objects.equals(this.links, defaultResponse.links) &&
        Objects.equals(this.status, defaultResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, updated, created, etag, links, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DefaultResponse {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
