/*
 * Videonetics Visual Computing Platform
 * API to access the Videonetics Visual Computing Platform for analytics events
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.VertexWithValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * HeatMap
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2018-12-06T15:05:09.757Z[GMT]")public class HeatMap {

  @SerializedName("max")
  private BigDecimal max = null;

  @SerializedName("verticesWithValue")
  private List<VertexWithValue> verticesWithValue = null;
  public HeatMap max(BigDecimal max) {
    this.max = max;
    return this;
  }

  

  /**
  * Get max
  * @return max
  **/
  @Schema(example = "5", description = "")
  public BigDecimal getMax() {
    return max;
  }
  public void setMax(BigDecimal max) {
    this.max = max;
  }
  public HeatMap verticesWithValue(List<VertexWithValue> verticesWithValue) {
    this.verticesWithValue = verticesWithValue;
    return this;
  }

  public HeatMap addVerticesWithValueItem(VertexWithValue verticesWithValueItem) {
    if (this.verticesWithValue == null) {
      this.verticesWithValue = new ArrayList<VertexWithValue>();
    }
    this.verticesWithValue.add(verticesWithValueItem);
    return this;
  }

  /**
  * Get verticesWithValue
  * @return verticesWithValue
  **/
  @Schema(description = "")
  public List<VertexWithValue> getVerticesWithValue() {
    return verticesWithValue;
  }
  public void setVerticesWithValue(List<VertexWithValue> verticesWithValue) {
    this.verticesWithValue = verticesWithValue;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HeatMap heatMap = (HeatMap) o;
    return Objects.equals(this.max, heatMap.max) &&
        Objects.equals(this.verticesWithValue, heatMap.verticesWithValue);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(max, verticesWithValue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HeatMap {\n");
    
    sb.append("    max: ").append(toIndentedString(max)).append("\n");
    sb.append("    verticesWithValue: ").append(toIndentedString(verticesWithValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
