/*
 * Videonetics Visual Computing Platform
 * API to access the Videonetics Visual Computing Platform for analytics events
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets locale
 */
@JsonAdapter(Locale.Adapter.class)
public enum Locale {
  EN("en"),
  BN("bn");

  private String value;

  Locale(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Locale fromValue(String text) {
    for (Locale b : Locale.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Locale> {
    @Override
    public void write(final JsonWriter jsonWriter, final Locale enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Locale read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Locale.fromValue(String.valueOf(value));
    }
  }
}
