/*
 * Videonetics Visual Computing Platform
 * API to access the Videonetics Visual Computing Platform for analytics events
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Links;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
/**
 * Video
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-09T12:31:58.860Z[GMT]")
public class Video {
  @SerializedName("_id")
  private UUID _id = null;

  @SerializedName("uri")
  private String uri = null;

  @SerializedName("startTimeStamp")
  private Long startTimeStamp = null;

  @SerializedName("endTimeStamp")
  private Long endTimeStamp = null;

  @SerializedName("updated")
  private OffsetDateTime updated = null;

  @SerializedName("created")
  private OffsetDateTime created = null;

  @SerializedName("etag")
  private String etag = null;

  @SerializedName("links")
  private Links links = null;

   /**
   * Get _id
   * @return _id
  **/
  @Schema(description = "")
  public UUID getId() {
    return _id;
  }

  public Video uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * Get uri
   * @return uri
  **/
  @Schema(description = "")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }

  public Video startTimeStamp(Long startTimeStamp) {
    this.startTimeStamp = startTimeStamp;
    return this;
  }

   /**
   * Video start timestamp in Unix epoch milliseconds
   * @return startTimeStamp
  **/
  @Schema(example = "1546041600000", description = "Video start timestamp in Unix epoch milliseconds")
  public Long getStartTimeStamp() {
    return startTimeStamp;
  }

  public void setStartTimeStamp(Long startTimeStamp) {
    this.startTimeStamp = startTimeStamp;
  }

  public Video endTimeStamp(Long endTimeStamp) {
    this.endTimeStamp = endTimeStamp;
    return this;
  }

   /**
   * Video end timestamp in Unix epoch milliseconds
   * @return endTimeStamp
  **/
  @Schema(example = "1546041600000", description = "Video end timestamp in Unix epoch milliseconds")
  public Long getEndTimeStamp() {
    return endTimeStamp;
  }

  public void setEndTimeStamp(Long endTimeStamp) {
    this.endTimeStamp = endTimeStamp;
  }

   /**
   * Get updated
   * @return updated
  **/
  @Schema(description = "")
  public OffsetDateTime getUpdated() {
    return updated;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(description = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public Video etag(String etag) {
    this.etag = etag;
    return this;
  }

   /**
   * Get etag
   * @return etag
  **/
  @Schema(example = "f7d6f2133d892ca3be7ee54d77c14bb15f75f72e", description = "")
  public String getEtag() {
    return etag;
  }

  public void setEtag(String etag) {
    this.etag = etag;
  }

  public Video links(Links links) {
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @Schema(description = "")
  public Links getLinks() {
    return links;
  }

  public void setLinks(Links links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Video video = (Video) o;
    return Objects.equals(this._id, video._id) &&
        Objects.equals(this.uri, video.uri) &&
        Objects.equals(this.startTimeStamp, video.startTimeStamp) &&
        Objects.equals(this.endTimeStamp, video.endTimeStamp) &&
        Objects.equals(this.updated, video.updated) &&
        Objects.equals(this.created, video.created) &&
        Objects.equals(this.etag, video.etag) &&
        Objects.equals(this.links, video.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, uri, startTimeStamp, endTimeStamp, updated, created, etag, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Video {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    startTimeStamp: ").append(toIndentedString(startTimeStamp)).append("\n");
    sb.append("    endTimeStamp: ").append(toIndentedString(endTimeStamp)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
