/**
 * Videonetics Visual Computing Platform
 * API to access the Videonetics Visual Computing Platform for analytics events
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { AccessStatus } from './accessStatus';
import { Enterprise } from './enterprise';
import { EnterpriseAccountStatus } from './enterpriseAccountStatus';
import { EnterpriseId } from './enterpriseId';


export interface EnterpriseDetail extends AccessStatus { 
    id: EnterpriseId;
    name: string;
    logo?: string;
    address?: string;
    contact?: string;
    accountStatus: EnterpriseAccountStatus;
}