/**
 * Videonetics Visual Computing Platform
 * API to access the Videonetics Visual Computing Platform for analytics events
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FaceAttributes { 
    smile?: number;
    gender?: FaceAttributes.GenderEnum;
    age?: number;
    glasses?: FaceAttributes.GlassesEnum;
}
export namespace FaceAttributes {
    export type GenderEnum = 'male' | 'female' | 'none';
    export const GenderEnum = {
        Male: 'male' as GenderEnum,
        Female: 'female' as GenderEnum,
        None: 'none' as GenderEnum
    };
    export type GlassesEnum = 'glasses' | 'noGalsses';
    export const GlassesEnum = {
        Glasses: 'glasses' as GlassesEnum,
        NoGalsses: 'noGalsses' as GlassesEnum
    };
}