/**
 * Videonetics Visual Computing Platform
 * API to access the Videonetics Visual Computing Platform for analytics events
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Links } from './links';


export interface Video { 
    readonly id?: string;
    uri?: string;
    /**
     * Video start timestamp in Unix epoch milliseconds
     */
    startTimeStamp?: number;
    /**
     * Video end timestamp in Unix epoch milliseconds
     */
    endTimeStamp?: number;
    readonly updated?: Date;
    readonly created?: Date;
    etag?: string;
    links?: Links;
}